/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef OPENGL_WIN32_GLEW_FREEIMAGE_GLM_PRIVATE_H
#define OPENGL_WIN32_GLEW_FREEIMAGE_GLM_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.1.1.46"
#define VER_MAJOR	0
#define VER_MINOR	1
#define VER_RELEASE	1
#define VER_BUILD	46
#define COMPANY_NAME	""
#define FILE_VERSION	""
#define FILE_DESCRIPTION	"Developed using the Dev-C++ IDE"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	"dimmy"
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"dimmy"
#define PRODUCT_NAME	"danbo"
#define PRODUCT_VERSION	""

#endif /*OPENGL_WIN32_GLEW_FREEIMAGE_GLM_PRIVATE_H*/
